id = "rst"
name = "reStructuredText"
grammar = "rst"
path_suffixes = ["rst"]
description = "reStructuredText support"
version = "0.1.0"
schema_version = 1
authors = ["Scott Trinh <scott@scotttrinh.com"]
repository = "https://github.com/scotttrinh/zed-rst"

[grammars.rst]
repository = "https://github.com/stsewd/tree-sitter-rst"
commit = "5120f6e59284cb8b85b450bd2db0bd352635ba9f"

[language_servers.esbonio]
name = "Esbonio"
language = "reStructuredText"
